# -*- coding: utf-8 -*-
"""Calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aiMSdYY2KozxvtV5qYOYdCNlUpAXEuhZ

CALCULATOR
"""

def add(x, y):
 return x+y

def subtract(x, y):
  return x-y

def divide(x, y):
  return x/y

def multiply(x, y):
  return x*y

def main():
  print("Simple python calculator")
  print("Made by Serah-.-.-.-.-.-.")

# LOOP TO PERFORM MULTIPLE OPERATIONS
while True:
  print("\nSelect operation")
  print("1. Add")
  print("2. Subtract")
  print("3. Divide")
  print("4. Multiply")
  print("5. Exit")

  # GET THE USER TO CHOOSE
  choice = input("Enter choice (1/2/3/4/5): ")
  if choice == '5':
    print("Leaving the calculator, Byee!")
  break # EXITING THE LOOP

# CHECK IF CHOICE IS VALID
if choice in ('1', '2', '3', '4'):
  try:
   num1 = float(input("Enter the first number: "))
   num2 = float(input("Enter the second number: "))
  except ValueError:
      print("Invalid number. Please enter a number.")

try:
    if choice == '1':
       result = add(num1, num2)
       op_symbol = '+'
    elif choice == '2':
         result = subtract(num1, num2)
         op_symbol = '-'
    elif choice == '3':
         result = multiply(num1, num2)
         op_symbol = '*'
    elif choice == '4':
         result = divide(num1, num2)
         op_symbol = '/'

    print(f"{num1} {op_symbol} {num2} = {result}")
except Exception as e:
         # catch any other errors (e.g., divide by zero)
     print(f"Error: {e}")

if __name__ == "__main__":
    main()

